spring:
  application:
    name: melvstein-portfolio-api
  security:
    user:
      name: melvstein
      password: melvstein0424
  jpa:
    hibernate:
      ddl-auto: validate # IMPORTANT when using flyway, set this to validate to avoid conflicts with the database schema
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-disabled: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/melvstein_portfolio_db
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  config:
    import: optional:file:.env[.properties]
  jackson:
    time-zone: Asia/Manila
app:
  api-key: ${API_KEY:test}
jwt:
  secret: ${JWT_SECRET:test}
  expiration:
    access-token: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000} # 1 hour in milliseconds
    refresh-token: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000} # 7 days in milliseconds
redis:
  expiration:
    refresh-token: ${REDIS_REFRESH_TOKEN_EXPIRATION:604800000} # 7 days in milliseconds
    user: ${REDIS_USER_EXPIRATION:3600000} # 1 hour in milliseconds
    jwt-token: ${REDIS_JWT_TOKEN_EXPIRATION:3600000} # 1 hour in milliseconds